services:
  notes-backend:
    container_name: backend-notes
    image: backend-notes
    restart: always
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "60:5000"
    volumes:
      - "./backend/src:/app/src"

  notes-frontend:
    container_name: frontend-notes
    image: frontend-notes
    restart: always
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "7000:3000"
    volumes:
      - "./frontend/build:/app/build"
    depends_on:
      - notes-backend

